### ISSUE TITLE
elliot did large ooooof (Create a lobby)

### ISSUE THREAD

**Issue by lexcorp** [w-henderson/Kascreech#8] opened 2021-05-17 17:22 UTC
When I try create a lobby, I get this message:

![image](https://user-images.githubusercontent.com/5751288/118530606-74ad4300-b70a-11eb-99a6-bce42723e7a5.png)

**Comment by w-henderson** [comment] 2021-05-17 17:24
The message says that Elliot did a large oof so I'll assign this issue to him.

**Comment by w-henderson** [comment] 2021-05-17 17:42
The issue is that you need to set the `SERVER_IP` constant in `chungus.ts` and `client.ts` and then recompile them as described in the README.

**Closed by w-henderson** 2021-05-17 17:42 UTC

**Comment by lexcorp** [comment] 2021-05-17 17:50
Thanks...
